apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ide
  template:
    metadata:
      labels:
        app: ide
    spec:
      containers:
      - image: theiaide/theia-cpp:latest
        name: ide

---

apiVersion: v1
kind: Service
metadata:
  name: ide
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ide"
    port: 8080
  selector:
    app: ide
