apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ide
  template:
    metadata:
      labels:
        app: ide
    spec:
      containers:
      - image: dickhub/linuxserver-codeserver:version-v3.9.3
        name: ide
      env:
      - name: PASSWORD
        value: "mqj.2006"
      - name: SUDO_PASSWORD
        value: "mqj.2006"

---

apiVersion: v1
kind: Service
metadata:
  name: ide
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ide"
    port: 8443
  selector:
    app: ide
